### ISSUE TITLE
TypeError: expected dtype object, got 'numpy.dtype[float64]' when animating

### ISSUE THREAD

**Issue by bjnorfolk** [dmentipl/plonk#34]
Hi, 

I'm trying to visualise my phantom simulation but I keep getting the error `TypeError: expected dtype object, got 'numpy.dtype[float64]'`

I've tried a few different methods of visualising the sim but the `TypeError` persists.

Here is a minimum working example using the minor and major phantom dumps.

```python
import plonk
import matplotlib.pyplot as plt

sim = plonk.load_simulation(prefix='disc', directory='hd100453_gas_disc_10mj_20au_low_acc/')

snaps = sim.snaps

units = {'position': 'au', 'density': 'g/cm^3'}

plonk.visualize.animation_images(filename='plots/hd100453_gas_disc_10mj_20au_low_acc.mp4',snaps=snaps,
	units=units,
	quantity='density',
	save_kwargs={'fps': 10, 'dpi': 300},)
```

This produces the following error.

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Volumes/phd_backup/phantom_dumps/animate_models.py in <module>
     16 'projection': 'cm'
     17 }
---> 18 plonk.animate(
     19 filename='animation.mp4',
     20 snaps=snaps,

/anaconda3/envs/py38/lib/python3.8/site-packages/plonk/visualize/animation.py in animate(filename, snaps, profiles, quantity, x, y, fig, adaptive_colorbar, adaptive_limits, text, text_kwargs, func_animation_kwargs, save_kwargs, **kwargs)
    149             )
    150         else:
--> 151             anim = animation_images(
    152                 filename=filename,
    153                 snaps=snaps,

/anaconda3/envs/py38/lib/python3.8/site-packages/plonk/visualize/animation.py in animation_images(filename, snaps, quantity, fig, adaptive_colorbar, text, text_kwargs, func_animation_kwargs, save_kwargs, **kwargs)
    247 
    248     if fig is None:
--> 249         ax = snaps[0].image(quantity=quantity, **kwargs)
    250         fig = ax.figure
    251         image = ax.images[0]

/anaconda3/envs/py38/lib/python3.8/site-packages/plonk/visualize/visualization.py in image(snap, quantity, x, y, interp, weighted, slice_normal, slice_offset, extent, units, ax, ax_kwargs, colorbar_kwargs, **kwargs)
    145     """
    146     with snap.context(cache=True):
--> 147         return _interpolation_plot(
    148             snap=snap,
    149             quantity=quantity,

/anaconda3/envs/py38/lib/python3.8/site-packages/plonk/visualize/visualization.py in _interpolation_plot(snap, quantity, x, y, kind, interp, weighted, slice_normal, slice_offset, extent, units, ax, ax_kwargs, colorbar_kwargs, **kwargs)
    339     # Interpolate data to plot
    340     num_pixels = _kwargs.pop('num_pixels', None)
--> 341     _data, _extent, _units = _interpolated_data(
    342         snap=snap,
    343         quantity=quantity,

/anaconda3/envs/py38/lib/python3.8/site-packages/plonk/visualize/visualization.py in _interpolated_data(snap, quantity, x, y, interp, weighted, slice_normal, slice_offset, extent, units, num_pixels)
    400 
    401     # Interpolate in code units
--> 402     interpolated_data = interpolate(
    403         snap=snap,
    404         quantity=quantity,

/anaconda3/envs/py38/lib/python3.8/site-packages/plonk/visualize/interpolation.py in interpolate(snap, quantity, x, y, interp, weighted, slice_normal, slice_offset, extent, num_pixels)
    125 
    126     if _quantity.ndim == 1:
--> 127         interpolated_data = scalar_interpolation(
    128             quantity=_quantity,
    129             x_coordinate=x,

/anaconda3/envs/py38/lib/python3.8/site-packages/plonk/visualize/interpolation.py in scalar_interpolation(quantity, x_coordinate, y_coordinate, dist_from_slice, extent, smoothing_length, particle_mass, hfact, weighted, num_pixels)
    208         shape (npixx, npixy).
    209     """
--> 210     return _interpolate(
    211         quantity=quantity,
    212         x_coordinate=x_coordinate,

/anaconda3/envs/py38/lib/python3.8/site-packages/plonk/visualize/interpolation.py in _interpolate(quantity, x_coordinate, y_coordinate, dist_from_slice, extent, smoothing_length, particle_mass, hfact, weighted, num_pixels)
    352         )
    353     else:
--> 354         interpolated_data = interpolate_projection(
    355             x=x_coordinate,
    356             y=y_coordinate,

TypeError: expected dtype object, got 'numpy.dtype[float64]'
```

+ OS: macOS 10.14.6
+ Python:  Python 3.8.5, Anaconda with conda 4.8
+ Plonk version: 0.7.3

I can share the dumps if you need.

Cheers,
Brodie

**Comment by bjnorfolk** [comment]
Additionally, I tried all my old scripts with my old phantom data for tasks such as making an image with `snap.image` and the same 'TypeError` is produced. 

I'm using the plonk from the conda-forge channel for reference.

**Comment by dmentipl** [comment]
Hi @bjnorfolk, thanks for raising this issue.

I tried to reproduce the issue but I couldn't. I suspect it's something to do with the numba package version. (The error is when calling `interpolate_projection` which is JITed with numba via `@numba.njit`.)

Could you please provide the output of `conda list --export`? Then I can reproduce your exact conda environment.

For clarity, it seems that a minimal reproducible example would be something like

```python
import plonk
snap = plonk.load_snap('my_snap.h5')
snap.image(quantity='density')
```

**Comment by bjnorfolk** [comment]
Hi @dmentipl thanks for the reply. I've updated numba and the code works. Cheers.

**Comment by Liu0813** [comment]
I also encountered the same problem, so which version of numba should be used?

**Comment by dmentipl** [comment]
Hi @Liu0813. I'm not exactly sure which versions Plonk is compatible with. However, the last time the tests were run via GitHub Actions, the numba version was 0.53.1. See [here](https://github.com/dmentipl/plonk/runs/2744960309?check_suite_focus=true#step:4:190). So I'm sure that version works. Could you please let me know what version you are having problems with?

**Comment by Liu0813** [comment]
Thank you for reply, I have updated the namba version to 0.53.1 and this error has disappeared. For older versions, such as 0.50.1, this problem may occur.
By the way, when generating animation, there is another type error, as following
```python
>>> plonk.animate(filename='animation.mp4', snaps=sim.snaps, quantity='density', extent=(-160, 160, -160, 160), units=units,adaptive_colorbar=False,save_kwargs={'fps': 10, 'dpi': 300})
  0%|                                                                                           | 0/21 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\Python3\lib\site-packages\plonk\visualize\animation.py", line 161, in animate
    **kwargs,
  File "D:\Program Files\Python3\lib\site-packages\plonk\visualize\animation.py", line 310, in animation_images
    anim.save(filepath, extra_args=['-vcodec', 'libx264'], **save_kwargs)
  File "D:\Program Files\Python3\lib\site-packages\matplotlib\animation.py", line 1140, in save
    writer.saving(self._fig, filename, dpi), \
  File "D:\Program Files\Python3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "D:\Program Files\Python3\lib\site-packages\matplotlib\animation.py", line 249, in saving
    self.setup(fig, outfile, dpi, *args, **kwargs)
  File "D:\Program Files\Python3\lib\site-packages\matplotlib\animation.py", line 338, in setup
    self._run()
  File "D:\Program Files\Python3\lib\site-packages\matplotlib\animation.py", line 350, in _run
    creationflags=subprocess_creation_flags)
  File "D:\Program Files\Python3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Program Files\Python3\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "D:\Program Files\Python3\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```
This may be caused by the version of matplotlib (==3.3.4). I have fixed this error by modifying the `animation.py`
https://github.com/dmentipl/plonk/blob/adc043b3fc532b653b9a273e989ab3907aac9306/src/plonk/visualize/animation.py#L310
into
```python
anim.save(filename, extra_args=['-vcodec', 'libx264'], **save_kwargs)
```

**Comment by dmentipl** [comment]
That's interesting. Thanks for bringing it to my attention.

I think the issue may be something to do with using `pathlib` and matplotlib animations in Windows. And maybe that's why using `filename`, which is a string works, and `filepath`, which is a `pathlib.Path` object, fails. According to the [matplotlib API](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.Animation.html#matplotlib.animation.Animation.save), the save function takes a string.

BTW I have only tested Plonk with Linux and macOS. If you would like to fix this I'm happy to take a pull request. Please see the [contributing guide](https://github.com/dmentipl/plonk/blob/main/CONTRIBUTING.md) for more.
